### PR TITLE
Was unable to compile with most recent version of Nim

### PR DESCRIPTION
**Pull request by xbello**
I changed some code that blocked the compilation with >1.2.0 version of Nim:

- String interpolation didn't work.
- A mismatched type at `delpid` blocked the compilation.
- In my linux box, processes are stored in /proc dirs, rather than files, so running processes were reported as killed.
- Changed the code to two-space tab as suggested in https://nim-lang.org/docs/nep1.html.

### CODE REVIEW

**Comment by bung87** [comment]
Can you confirm that it runs well ? as this repo 2 years ago and has no CI test, I almost forgot everything. 
if you can confirm that or has some CI test, I'll merge this, looks good.

**Comment by xbello** [comment]
I'll try to make some tests, but I don't have any MacOS at hand. All the tests are going to be pure Linux.

**Comment by bung87** [comment]
> I'll try to make some tests, but I don't have any MacOS at hand. All the tests are going to be pure Linux.

Thanks! that's really nice.

**Comment by bung87** [comment]
Thanks ! I cherry pick this PR and run test passed. close this.

**Pull request closed without merging**
